version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: niekform
      POSTGRES_USER: niekform
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
